package com.devson.vedtube.data.provider.youtube.piped

import com.devson.vedtube.data.provider.youtube.piped.model.PipedStreamResponse
import com.devson.vedtube.domain.model.AudioStream
import com.devson.vedtube.domain.model.PlaybackSource
import com.devson.vedtube.domain.model.SubtitleTrack
import com.devson.vedtube.domain.model.VideoStream

object PipedMapper {

    private const val DEFAULT_EXPIRY_DURATION_MS = 6 * 3600 * 1000L

    fun map(response: PipedStreamResponse, videoId: String): PlaybackSource {
        val videoStreams = response.videoStreams.mapNotNull { stream ->
            val url = stream.url
            if (url.isNullOrBlank()) null
            else {
                val res = stream.quality ?: "${stream.height ?: 360}p"
                val height = stream.height ?: parseHeight(res)
                val width = stream.width ?: calculateWidth(height)
                VideoStream(
                    url = url,
                    resolution = res,
                    width = width,
                    height = height,
                    bitrate = stream.bitrate ?: 0,
                    fps = stream.fps ?: 30,
                    codec = stream.codec,
                    mimeType = stream.mimeType ?: "video/mp4",
                    isVideoOnly = stream.videoOnly ?: false,
                    format = stream.format
                )
            }
        }

        val audioStreams = response.audioStreams.mapNotNull { stream ->
            val url = stream.url
            if (url.isNullOrBlank()) null
            else {
                AudioStream(
                    url = url,
                    bitrate = stream.bitrate ?: 0,
                    averageBitrate = stream.bitrate ?: 0,
                    codec = stream.codec,
                    mimeType = stream.mimeType ?: "audio/mp4",
                    format = stream.format
                )
            }
        }

        val subtitles = response.subtitles.mapNotNull { sub ->
            val url = sub.url
            if (url.isNullOrBlank()) null
            else {
                val code = sub.code.orEmpty()
                SubtitleTrack(
                    url = url,
                    languageCode = code,
                    languageName = sub.name ?: code.ifBlank { "Unknown" },
                    mimeType = sub.mimeType ?: "text/vtt",
                    isAutoGenerated = sub.autoGenerated ?: false
                )
            }
        }

        val firstUrl = videoStreams.firstOrNull()?.url ?: audioStreams.firstOrNull()?.url
        val expiresAt = extractExpirationTimestamp(firstUrl)

        return PlaybackSource(
            videoId = videoId,
            title = response.title,
            uploaderName = response.uploader,
            streams = videoStreams,
            audioStreams = audioStreams,
            subtitles = subtitles,
            durationMs = response.duration?.let { if (it > 0) it * 1000L else null },
            expiresAtTimestampMs = expiresAt,
            dashManifestUrl = response.dash,
            hlsManifestUrl = response.hls
        )
    }

    private fun extractExpirationTimestamp(url: String?): Long {
        if (url.isNullOrBlank()) return System.currentTimeMillis() + DEFAULT_EXPIRY_DURATION_MS

        val expireParam = if (url.contains("expire=")) {
            url.substringAfter("expire=").substringBefore("&")
        } else {
            null
        }

        val seconds = expireParam?.toLongOrNull()
        return if (seconds != null && seconds > 0) {
            seconds * 1000L
        } else {
            System.currentTimeMillis() + DEFAULT_EXPIRY_DURATION_MS
        }
    }

    private fun parseHeight(resolution: String): Int {
        val digits = resolution.filter { it.isDigit() }
        return digits.toIntOrNull() ?: 360
    }

    private fun calculateWidth(height: Int): Int {
        return if (height > 0) (height * 16) / 9 else 640
    }
}
