package com.devson.vedtube.data.provider.youtube.invidious

import com.devson.vedtube.data.provider.youtube.invidious.model.InvidiousStreamResponse
import com.devson.vedtube.domain.model.AudioStream
import com.devson.vedtube.domain.model.PlaybackSource
import com.devson.vedtube.domain.model.SubtitleTrack
import com.devson.vedtube.domain.model.VideoStream

object InvidiousMapper {

    private const val DEFAULT_EXPIRY_DURATION_MS = 6 * 3600 * 1000L

    fun map(response: InvidiousStreamResponse, videoId: String): PlaybackSource {
        val videoStreams = mutableListOf<VideoStream>()

        // 1. Progressive streams (formatStreams)
        response.formatStreams.forEach { stream ->
            val url = stream.url
            if (!url.isNullOrBlank()) {
                val res = stream.qualityLabel ?: stream.resolution ?: stream.quality ?: "720p"
                val height = parseHeight(res)
                val width = calculateWidth(height)
                val isMp4 = stream.container.equals("mp4", ignoreCase = true) || stream.type?.contains("video/mp4") == true

                videoStreams.add(
                    VideoStream(
                        url = url,
                        resolution = res,
                        width = width,
                        height = height,
                        bitrate = stream.bitrate?.toIntOrNull() ?: 0,
                        fps = stream.fps ?: 30,
                        codec = extractCodec(stream.type),
                        mimeType = if (isMp4) "video/mp4" else "video/webm",
                        isVideoOnly = false,
                        format = stream.container ?: "mp4"
                    )
                )
            }
        }

        // 2. Adaptive video streams
        response.adaptiveFormats.forEach { stream ->
            val url = stream.url
            val type = stream.type.orEmpty()
            if (!url.isNullOrBlank() && type.startsWith("video/")) {
                val res = stream.qualityLabel ?: stream.resolution ?: "720p"
                val height = parseHeight(res)
                val width = calculateWidth(height)

                videoStreams.add(
                    VideoStream(
                        url = url,
                        resolution = res,
                        width = width,
                        height = height,
                        bitrate = stream.bitrate?.toIntOrNull() ?: 0,
                        fps = stream.fps ?: 30,
                        codec = extractCodec(type),
                        mimeType = if (type.contains("mp4")) "video/mp4" else "video/webm",
                        isVideoOnly = true,
                        format = stream.container ?: "mp4"
                    )
                )
            }
        }

        // 3. Adaptive audio streams
        val audioStreams = response.adaptiveFormats.mapNotNull { stream ->
            val url = stream.url
            val type = stream.type.orEmpty()
            if (!url.isNullOrBlank() && type.startsWith("audio/")) {
                AudioStream(
                    url = url,
                    bitrate = stream.bitrate?.toIntOrNull() ?: 128_000,
                    averageBitrate = stream.bitrate?.toIntOrNull() ?: 128_000,
                    codec = extractCodec(type),
                    mimeType = if (type.contains("mp4")) "audio/mp4" else "audio/webm",
                    format = stream.container ?: "m4a"
                )
            } else {
                null
            }
        }

        // 4. Captions / Subtitles
        val subtitles = response.captions.mapNotNull { sub ->
            val url = sub.url
            if (url.isNullOrBlank()) null
            else {
                val code = sub.languageCode.orEmpty()
                SubtitleTrack(
                    url = url,
                    languageCode = code,
                    languageName = sub.label ?: code.ifBlank { "Unknown" },
                    mimeType = "text/vtt",
                    isAutoGenerated = false
                )
            }
        }

        val firstUrl = videoStreams.firstOrNull()?.url ?: audioStreams.firstOrNull()?.url
        val expiresAt = extractExpirationTimestamp(firstUrl)

        return PlaybackSource(
            videoId = videoId,
            title = response.title,
            uploaderName = response.author,
            streams = videoStreams,
            audioStreams = audioStreams,
            subtitles = subtitles,
            durationMs = response.lengthSeconds?.let { if (it > 0) it * 1000L else null },
            expiresAtTimestampMs = expiresAt,
            dashManifestUrl = response.dashUrl,
            hlsManifestUrl = response.hlsUrl
        )
    }

    private fun extractCodec(type: String?): String? {
        if (type == null || !type.contains("codecs=")) return null
        return type.substringAfter("codecs=\"").substringBefore("\"")
    }

    private fun extractExpirationTimestamp(url: String?): Long {
        if (url.isNullOrBlank()) return System.currentTimeMillis() + DEFAULT_EXPIRY_DURATION_MS

        val expireParam = if (url.contains("expire=")) {
            url.substringAfter("expire=").substringBefore("&")
        } else {
            null
        }

        val seconds = expireParam?.toLongOrNull()
        return if (seconds != null && seconds > 0) {
            seconds * 1000L
        } else {
            System.currentTimeMillis() + DEFAULT_EXPIRY_DURATION_MS
        }
    }

    private fun parseHeight(resolution: String): Int {
        val digits = resolution.filter { it.isDigit() }
        return digits.toIntOrNull() ?: 360
    }

    private fun calculateWidth(height: Int): Int {
        return if (height > 0) (height * 16) / 9 else 640
    }
}
