package com.devson.vedtube.data.provider.youtube.piped.model

import kotlinx.serialization.Serializable

@Serializable
data class PipedStreamResponse(
    val title: String? = null,
    val description: String? = null,
    val uploadDate: String? = null,
    val uploader: String? = null,
    val uploaderUrl: String? = null,
    val uploaderAvatar: String? = null,
    val thumbnailUrl: String? = null,
    val hls: String? = null,
    val dash: String? = null,
    val duration: Long? = null,
    val views: Long? = null,
    val likes: Long? = null,
    val audioStreams: List<PipedAudioStream> = emptyList(),
    val videoStreams: List<PipedVideoStream> = emptyList(),
    val subtitles: List<PipedSubtitle> = emptyList()
)

@Serializable
data class PipedAudioStream(
    val url: String? = null,
    val format: String? = null,
    val bitrate: Int? = null,
    val codec: String? = null,
    val mimeType: String? = null
)

@Serializable
data class PipedVideoStream(
    val url: String? = null,
    val format: String? = null,
    val quality: String? = null,
    val width: Int? = null,
    val height: Int? = null,
    val bitrate: Int? = null,
    val fps: Int? = null,
    val codec: String? = null,
    val videoOnly: Boolean? = null,
    val mimeType: String? = null
)

@Serializable
data class PipedSubtitle(
    val url: String? = null,
    val code: String? = null,
    val name: String? = null,
    val autoGenerated: Boolean? = null,
    val mimeType: String? = null
)
