package com.devson.vedtube.domain.model

/**
 * Domain representation of a subtitle or closed-caption track.
 */
data class SubtitleTrack(
    val url: String,
    val languageCode: String,
    val languageName: String,
    val mimeType: String = "text/vtt",
    val isAutoGenerated: Boolean = false
)
