package com.devson.vedtube.data.provider.youtube

import com.devson.vedtube.domain.model.AudioStream
import com.devson.vedtube.domain.model.PlaybackSource
import com.devson.vedtube.domain.model.SubtitleTrack
import com.devson.vedtube.domain.model.VideoStream
import org.schabi.newpipe.extractor.stream.StreamInfo

/**
 * Maps raw [StreamInfo] extractor data into clean, provider-agnostic [PlaybackSource] models.
 */
object YoutubePlaybackMapper {

    private const val DEFAULT_EXPIRY_DURATION_MS = 6 * 3600 * 1000L // 6 hours

    fun map(streamInfo: StreamInfo, videoId: String): PlaybackSource {
        val videoStreams = mutableListOf<VideoStream>()

        // 1. Progressive streams (combined video + audio)
        streamInfo.videoStreams.orEmpty().forEach { stream ->
            val url = stream.content ?: stream.url
            if (!url.isNullOrBlank()) {
                val res = stream.resolution ?: "${stream.height}p"
                val h = if (stream.height > 0) stream.height else parseHeight(res)
                val w = if (stream.width > 0) stream.width else calculateWidth(h)
                videoStreams.add(
                    VideoStream(
                        url = url,
                        resolution = res,
                        width = w,
                        height = h,
                        bitrate = if (stream.bitrate > 0) stream.bitrate else 0,
                        fps = if (stream.fps > 0) stream.fps else 30,
                        codec = stream.codec,
                        mimeType = stream.format?.mimeType ?: "video/mp4",
                        isVideoOnly = stream.isVideoOnly,
                        format = stream.format?.name
                    )
                )
            }
        }

        // 2. Adaptive video-only streams
        streamInfo.videoOnlyStreams.orEmpty().forEach { stream ->
            val url = stream.content ?: stream.url
            if (!url.isNullOrBlank()) {
                val res = stream.resolution ?: "${stream.height}p"
                val h = if (stream.height > 0) stream.height else parseHeight(res)
                val w = if (stream.width > 0) stream.width else calculateWidth(h)
                videoStreams.add(
                    VideoStream(
                        url = url,
                        resolution = res,
                        width = w,
                        height = h,
                        bitrate = if (stream.bitrate > 0) stream.bitrate else 0,
                        fps = if (stream.fps > 0) stream.fps else 30,
                        codec = stream.codec,
                        mimeType = stream.format?.mimeType ?: "video/mp4",
                        isVideoOnly = true,
                        format = stream.format?.name
                    )
                )
            }
        }

        // 3. Audio streams
        val audioStreams = streamInfo.audioStreams.orEmpty().mapNotNull { stream ->
            val url = stream.content ?: stream.url
            if (url.isNullOrBlank()) null
            else {
                AudioStream(
                    url = url,
                    bitrate = if (stream.bitrate > 0) stream.bitrate else stream.averageBitrate,
                    averageBitrate = stream.averageBitrate,
                    codec = stream.codec,
                    mimeType = stream.format?.mimeType ?: "audio/mp4",
                    format = stream.format?.name
                )
            }
        }

        // 4. Subtitle tracks
        val subtitles = streamInfo.subtitles.orEmpty().mapNotNull { sub ->
            val url = sub.content ?: sub.url
            if (url.isNullOrBlank()) null
            else {
                val langCode = sub.languageTag ?: sub.locale?.language ?: ""
                SubtitleTrack(
                    url = url,
                    languageCode = langCode,
                    languageName = sub.displayLanguageName ?: langCode.ifBlank { "Unknown" },
                    mimeType = sub.format?.mimeType ?: "text/vtt",
                    isAutoGenerated = sub.isAutoGenerated
                )
            }
        }

        // 5. Expiration timestamp
        val firstStreamUrl = videoStreams.firstOrNull()?.url ?: audioStreams.firstOrNull()?.url
        val expiresAt = extractExpirationTimestamp(firstStreamUrl)

        return PlaybackSource(
            videoId = videoId,
            title = streamInfo.name,
            uploaderName = streamInfo.uploaderName,
            streams = videoStreams,
            audioStreams = audioStreams,
            subtitles = subtitles,
            durationMs = if (streamInfo.duration > 0) streamInfo.duration * 1000L else null,
            expiresAtTimestampMs = expiresAt,
            dashManifestUrl = streamInfo.dashMpdUrl,
            hlsManifestUrl = streamInfo.hlsUrl
        )
    }

    private fun extractExpirationTimestamp(url: String?): Long {
        if (url.isNullOrBlank()) return System.currentTimeMillis() + DEFAULT_EXPIRY_DURATION_MS

        val expireParam = if (url.contains("expire=")) {
            url.substringAfter("expire=").substringBefore("&")
        } else {
            null
        }

        val seconds = expireParam?.toLongOrNull()
        return if (seconds != null && seconds > 0) {
            seconds * 1000L
        } else {
            System.currentTimeMillis() + DEFAULT_EXPIRY_DURATION_MS
        }
    }

    private fun parseHeight(resolution: String): Int {
        val digits = resolution.filter { it.isDigit() }
        return digits.toIntOrNull() ?: 360
    }

    private fun calculateWidth(height: Int): Int {
        return if (height > 0) (height * 16) / 9 else 640
    }
}
